# Generated by Django 2.2.6 on 2019-11-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191101_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realor',
            new_name='realtor',
        ),
    ]
